version: '3'
services:
   yunohost:
     image: yunohost:local-2019-12-01
     restart: unless-stopped
     hostname: yuno.vaneckonline.net
     privileged: true
     ports:
       - '53:53/udp'
       - '80:80'
       - '443:443'
     volumes:
       - 'yuno-data-vol:/home'
       - /etc/localtime:/etc/localtime:ro
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
     networks:
       - yunonet
volumes:
  yuno-data-vol:
networks:
  yunonet:
